spring:
  profiles: dev
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5432/test
    pool:
      enabled: true
      initial-size: 10
      max-idle-time: 1m
      max-size: 30
  webflux:
    base-path: /${spring.application.name}

datasources:
  redis:
    nodes: localhost:6379
    read-time-out: 5000
    retry-attempts: 5
    retry-interval: 1500
    database-number: 1
    connection-pool-size: 64
    threads: 4
    nettyThreads: 4


mock:
  default-ttl-ms: 1800000

management:
  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.50,0.75,0.95,0.99
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
